#!/usr/bin/env python

import http.client, urllib

import sys, os
sys.path.append(os.path.join(os.path.dirname(__file__), '../', 'lib'))
import fpc

TOKEN = fpc.settings("po_token")
USER = fpc.settings("po_user")

def pushover(message):
	conn = http.client.HTTPSConnection("api.pushover.net:443")
	conn.request("POST", "/1/messages.json",
			urllib.parse.urlencode({
				"token": TOKEN,
				"user": USER,
				"message": message,
				}), {"Content-type": "application/x-www-form-urlencoded"})
	conn.getresponse()

if __name__ == "__main__":
	if len(sys.argv) == 2:
		pushover(sys.argv[1])

	else:
		sys.exit("Error: Incorrect number of arguments were given.")
