#!/usr/bin/env bash

# Run without debugging mode
if (( $# == 0 )); then
  export FLASK_APP=fpc.py
  export FLASK_DEBUG=0
  flask run
# Run in debugging mode for development purposes
elif (( $# == 1 )); then
  export FLASK_APP=fpc.py
  export FLASK_DEBUG=1
  flask run
fi
