#!/usr/bin/env python

import sys, os
import sqlite3
import datetime, time

DIR_NAME = os.path.split(os.path.abspath(sys.argv[0]))[0]

def fetch_input():
    date = input("\nEnter the date: ")
    comment = input("Enter the comment: ")

    try:
        if "/" in date:
            date = datetime.datetime.strptime(date, "%d/%m/%Y")
        elif "-" in date:
            date = datetime.datetime.strptime(date, "%U-%u %Y")
        if comment is "":
            sys.exit("[ERROR] The comment was empty")
    except ValueError:
        sys.exit("[ERROR] The format for the date was wrong")

    return date.strftime("%U-%u"), date.strftime("%Y"), comment


def db_comment_add(date, year, comment):
    # Format of the SUMMARY table:
    # ('32-5', 0.24, 0.0, None)
    conn = sqlite3.connect(DIR_NAME + "/" + str(year) + ".db")
    c = conn.cursor()

    # Check if an entry for the day exists
    c.execute('SELECT rowid FROM SUMMARY WHERE date = (?)', (date,))
    if c.fetchone() is None:
        sys.exit("[ERROR] No entry found for this day on the DB")
    else:
        c.execute('UPDATE SUMMARY SET comments = (?) WHERE date = (?)', (comment, date))

    conn.commit()
    conn.close()

########
# Main #
########
if __name__ == '__main__':
    print("The date is: " + time.strftime("%d/%m/%Y"))
    print("The date is: " + time.strftime("%U-%w-%Y")) #0 is sunday 6 is saturday
    print("The date is: " + time.strftime("%W-%u-%Y")) #1 is monday 7 is sunday

    date = input("\nEnter the date: ")
    comment = input("Enter the comment: ")

    try:
        if "/" in date:
            date = datetime.datetime.strptime(date, "%d/%m/%Y")
        elif "-" in date:
            date = datetime.datetime.strptime(date, "%W-%u-%Y")
        if comment is "":
            sys.exit("[ERROR] The comment was empty")
    except ValueError:
        sys.exit("[ERROR] The format for the date was wrong")

    year = date.strftime("%Y")
    date = date.strftime("%W-%u")
    db_comment_add(date, year, comment)
