#!/usr/bin/env python

# Description: We receive the week number and we print data
# from all the week.

import time
import sqlite3
import sys, os

DIR_NAME = os.path.split(os.path.abspath(sys.argv[0]))[0]
YEAR = time.strftime("%Y")
WEEK_NUMBER =  time.strftime("%U")
DB_NAME = DIR_NAME + "/" + YEAR + ".db"

def db_print(db_cursor):
    date = WEEK_NUMBER + "-%"
    for row in db_cursor.execute('SELECT * FROM FPL WHERE date LIKE ? ORDER BY date', (date,)):
        print(row)
    print("---- Summary ----")
    for row in db_cursor.execute('SELECT * FROM SUMMARY ORDER BY date DESC limit 14'):
        print(row)

########
# Main #
########
if __name__ == '__main__':
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    print("The current week number is:", WEEK_NUMBER)
    db_print(c)
    conn.close()
