#!/usr/bin/env python

import sqlite3
from flask import Flask, render_template
from flask import g
from flask import request, redirect

import time
import os

###############
# Global vars #
###############
app = Flask(__name__)
# Disable whitespace and newline weirdness
app.jinja_env.trim_blocks = True
app.jinja_env.lstrip_blocks = True

THRESHOLD = 0.12
WEEK = time.strftime("%W")
YEAR = time.strftime("%Y")

####################
# Helper functions #
####################
# Keeps displaying days in the website as long as those days are in the database
def until_week_not_empty(year, week_number):
    while week_number > -1:
        query_str = str(year) + "-" + str(week_number) + "-%"
        c = g.db.execute("SELECT rowid FROM FPC WHERE date LIKE (?)", (query_str,)).fetchone()

        if c is not None:
            break
        else:
            week_number = week_number - 1

    if week_number == -1:
        return(week_number)
    else:
        return(week_number)


def file_exists(file_name):
    if os.path.exists(file_name):
        return True
    else:
        return False

#######################
# DB helper funcions  #
#######################
def connect_db(db_name):
    """Connects to the specified database"""
    db = sqlite3.connect(db_name)
    return db

@app.teardown_appcontext
def close_connection(exception):
    """Closes the database at the end of the request"""
    if hasattr(g, 'db'):
        g.db.close()

##################
#     FPC        #
##################
@app.route('/')
def index():
    return redirect('/week/' + YEAR + '/' + WEEK)

@app.route('/week/<int:year>/<int:week_number>')
def week(year, week_number):
    # Open the DB
    if file_exists("db/data.db"):
        g.db = connect_db("db/data.db")
    else:
        return error()
    # The query to the DB returns a tuple for each hour of the day. E.g.
    # ('2016-29-0', 0, 0.12, 0.21, 0.57, 78)
    # 29-0 -> The first day of week 29 of 2016
    # 0    -> Hour 0:00 for this day
    # 0.12 -> Cost
    # 0.21 -> kWh
    # 0.57 -> kWh rate
    # 78   -> Average temperature
    week_number = until_week_not_empty(year, week_number)
    if week_number == -1:
        return render_template('error.html')

    # List of list of tuples.
    # The outter list represents a week
    # The inner loop represents a day of the week
    # The tuple represents the hours of that day
    week = []
    # List of tuples
    day_summary = []
    for day in range(1, 8):
        week_day = str(year) + "-" + str(week_number) + "-" + str(day)
        # Only append data to week when we find an entry for that day in the DB
        if g.db.execute("SELECT rowid FROM FPC WHERE date=?", (week_day,)).fetchone():
            week.append(g.db.execute("SELECT * FROM FPC WHERE date=?", (week_day,)).fetchall())
            day_summary.append(g.db.execute("SELECT * FROM SUMMARY WHERE date=?", (week_day,)).fetchall()[0])

    return render_template('week.html',
            summary         = day_summary,
            year            = year,
            week            = week,
            week_number     = int(week_number),
            hours_in_a_day  = list(range(0, 24)),
            threshold       = THRESHOLD)

@app.route('/error')
def error():
    return render_template('error.html')

@app.route('/about')
def about():
    return render_template('about.html')

@app.route('/yearly')
def yearly():
    return render_template('yearly.html')

########
# Main #
########
if __name__ == '__main__':
    app.run(debug=True)
